---
all:
  hosts:
    nexus-01:
      ansible_host: 111.88.254.144
      ansible_python_interpreter: /usr/bin/python3.11
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: yc-user
